### PR TITLE
please accept

### PR DESCRIPTION
**Pull request by tausiq2003**
Hi there, myself tausiq. I am adding a new code to your repo i.e.password generator. Hope you will like it my code.
In my code, I have used password length between 10 and 20.
Hope you will like it.
Thank you.

### CODE REVIEW

**Comment by xlogix** [comment]
Though it's nice. This won't be truly random since random methods aren't truly random without salt like time.

**Comment by tausiq2003** [comment]
Yeah but its acceptable also random is machine dependent

**Comment by xlogix** [comment]
Also, if you can, then try to improve your password generator with a random salt.

**Comment by tausiq2003** [comment]
ok I am closing the pr

**Pull request closed without merging**
