### PR TITLE
modified readme file

### PR DESCRIPTION
**Pull request by tejasri19**

### CODE REVIEW

**Comment by arghac14** [comment]
@tejasri19 there is a conflict, can you please check once again?

**Comment by tejasri19** [comment]
> @tejasri19 there is a conflict, can you please check once again?

unable to do it, need help!

**Comment by arghac14** [comment]
@tejasri19 please pull the changes of README first then add your changes, and then only send a pull request.Hope that helps!

**Comment by xlogix** [comment]
@tejasri19 Resolved your conflict. Thanks for contributing!

**Pull request merged**
